### ISSUE TITLE
VersionAttribute is null

### ISSUE THREAD

**Issue by generik0** [wieslawsoltes/PackageReferenceEditor#1]
Hi

This is a cool package., especially nuget really doesn't work well for updates anymore :-(

I get v.VersionAttribute.Value == null.  Is this because of the new VS csproj format?

![image](https://user-images.githubusercontent.com/2411563/39957606-0b3e7704-55f6-11e8-815b-47b72fa9c1ca.png)

**Comment by generik0** [comment]
THis is a potential fix. And it appears to work -):
![image](https://user-images.githubusercontent.com/2411563/39957682-4eb88cf8-55f7-11e8-8918-92c2e627e977.png)

**Comment by jbastnagelcwp** [comment]
I made a pull request (#2) to fix this. Hopefully @wieslawsoltes can verify and merge it quickly.
